[package]
name = "libectf"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
aes = "0.8.4"
bincode = { version = "2.0.0-rc.3", features = ['serde', 'derive', 'alloc'], default-features = false }
cipher = "0.4.4"
sha2 = { version = "0.10.8", default-features = false }
